### ISSUE TITLE
consider using the builtin mixin for authentication 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/bundlejoy#6]
https://github.com/dfloresca/bundlejoy/blob/8ec66d8c29e140c15b9b7121be025a300a07a334/social/views.py#L39

using a mixin will also give you 401 handling and redirection handlign and the ability to drop some of the branching logic in the view functions

**Comment by dfloresca** [comment]
using the mixin looked like it would require refactoring my views as class views. I discovered the permission_required decorator and used that to redirect to the login page and remove the branched logic in the views.
